services:
  a8r:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: a8r
        PORT: 8080
    ports: ["8080:8080"]
    environment:
      DATABASE_HOST: a8r-mariadb
      DATABASE_PORT: 3306

  telegram:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: telegram
        PORT: 5050
    ports: ["5050:5050"]
    environment:
      DATABASE_HOST: telegram-mariadb
      DATABASE_PORT: 3306
      A8R_BASE_URL: http://a8r:8080

  a8r-mariadb:
    ports: ["3306:3306"]
    volumes:
      - a8r_mariadb_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: a8r
      MARIADB_ROOT_PASSWORD: root

  telegram-mariadb:
    ports: ["3307:3306"]
    volumes:
      - telegram_mariadb_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: telegram
      MARIADB_ROOT_PASSWORD: root
