services:
  mariadb-core: &mariadb-core
    image: mariadb:11.2.5@sha256:1363d4688aed0a0c3ddacb6e1b0a93dcfd765e557cb05e207b46bc8c60e376af
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  a8r:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: a8r
        PORT: 8080
    environment:
      DATABASE_HOST: a8r-mariadb
      DATABASE_PORT: 3306
    ports: [ "8080:8080" ]
    depends_on:
      a8r-mariadb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
      interval: 5s
      timeout: 1s
      retries: 60

  a8r-mariadb:
    <<: *mariadb-core
    ports: [ "3306:3306" ]
    volumes:
      - a8r_mariadb_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: a8r
      MARIADB_ROOT_PASSWORD: root

  telegram:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: telegram
        PORT: 5050
    environment:
      DATABASE_HOST: telegram-mariadb
      DATABASE_PORT: 3306
    ports: [ "5050:5050" ]
    depends_on:
      telegram-mariadb:
        condition: service_healthy
      a8r:
        condition: service_healthy

  telegram-mariadb:
    <<: *mariadb-core
    ports: [ "3307:3306" ]
    volumes:
      - telegram_mariadb_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: telegram
      MARIADB_ROOT_PASSWORD: root

volumes:
  a8r_mariadb_data:
  telegram_mariadb_data:
