services:
  mariadb:
    image: mariadb:11.2.6@sha256:ff87d49107a1e4878c63c3a3132bfdf628e6732879b8e4ceb72e041206d3aece
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:11.9.1@sha256:0abb0531e0df0841e6f11e872d5b17cfabde5a14454876ae8abf4e076b324423
    command: migrate
    depends_on:
      mariadb:
        condition: service_healthy

  a8r:
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
      interval: 5s
      timeout: 1s
      retries: 60

  telegram:
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      a8r:
        condition: service_healthy

  ngrok:
    image: ngrok/ngrok:3@sha256:d6f0efb2330375e30505e67a542301e8aaef87da695953e81936ca23b8a7babd
    command: http host.docker.internal:5050

  mock-server:
    image: mockserver/mockserver:5.15.0@sha256:0f9ef78c94894ac3e70135d156193b25e23872575d58e2228344964273b4af6b
    command: >
      -logLevel DEBUG 
      -serverPort 1080

volumes:
  mariadb_data:
