services:
  a8r:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: a8r
        PORT: 8080
    ports: ["8080:8080"]
    environment:
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306

  telegram:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: telegram
        PORT: 5050
    ports: ["5050:5050"]
    environment:
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      A8R_BASE_URL: http://a8r:8080

  mariadb:
    ports: ["3306:3306"]
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: mariadb
      MARIADB_ROOT_PASSWORD: root

  ngrok:
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports: ["4040:4040"]

  flyway:
    environment:
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
      FLYWAY_BASELINE_ON_MIGRATE: true
      FLYWAY_BASELINE_VERSION: 0
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/mariadb
      FLYWAY_USER: root
      FLYWAY_PASSWORD: root
    volumes:
      - ./.github/environment/migrations:/flyway/sql

  mock-server:
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: true
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/init.json
    volumes:
      - ./.github/environment/mock/init.json:/config/init.json
    ports: ["1080:1080"]
