services:
  mariadb:
    image: mariadb:11.2.6@sha256:ff87d49107a1e4878c63c3a3132bfdf628e6732879b8e4ceb72e041206d3aece
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:11.8.1@sha256:b001b9463f6db9612e58c198a6dbc6a4315e8201a430d407a38e6a32210f39b8
    command: migrate
    depends_on:
      mariadb:
        condition: service_healthy

  a8r:
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
      interval: 5s
      timeout: 1s
      retries: 60

  telegram:
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      a8r:
        condition: service_healthy

  ngrok:
    image: ngrok/ngrok:3@sha256:8d2d2b134398d186934140626bfa1638e6ae079dc8dd4aaac88707e309406880
    command: http host.docker.internal:5050

  mock-server:
    image: mockserver/mockserver:5.15.0@sha256:0f9ef78c94894ac3e70135d156193b25e23872575d58e2228344964273b4af6b
    command: >
      -logLevel DEBUG 
      -serverPort 1080

volumes:
  mariadb_data:
