services:
  mariadb:
    image: mariadb:11.2.6@sha256:ff87d49107a1e4878c63c3a3132bfdf628e6732879b8e4ceb72e041206d3aece
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:12.8.1@sha256:b8a2d72926b98234c1fb8f45659fd23d8a001af9ee7f450326aa46af14d447bb
    command: migrate
    depends_on:
      mariadb:
        condition: service_healthy

  spring-webflux-aggregator:
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD",
          "busybox",
          "wget",
          "-q",
          "-O",
          "/dev/null",
          "http://localhost:8080/health/ping",
        ]
      interval: 5s
      timeout: 5s
      retries: 60

  spring-telegram-webhook:
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      spring-webflux-aggregator:
        condition: service_healthy

  ngrok:
    image: ngrok/ngrok:3@sha256:fc148db24a14f151a8d07101b01f00d116e58609c47334a8034edb1870f92c21
    command: http host.docker.internal:5050

  mock-server:
    image: mockserver/mockserver:7.0.0@sha256:95a393d14e441684758dda2b8f473db7683f97ad74e0975620b95a34a85de49f
    profiles: ["mock"]
    command: >
      -logLevel DEBUG 
      -serverPort 1080

volumes:
  mariadb_data:
