services:
  spring-webflux-aggregator:
    build:
      context: ../../
      dockerfile: tools/docker/Dockerfile
      args:
        MODULE: spring-webflux-aggregator
        PORT: 8080
        GRADLE_OPTS: ${GRADLE_OPTS}
    ports: ["8080:8080"]
    environment:
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306

  spring-telegram-webhook:
    build:
      context: ../../
      dockerfile: tools/docker/Dockerfile
      args:
        MODULE: spring-telegram-webhook
        PORT: 5050
        GRADLE_OPTS: ${GRADLE_OPTS}
    ports: ["5050:5050"]
    environment:
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      A8R_BASE_URL: http://spring-webflux-aggregator:8080

  mariadb:
    ports: ["3306:3306"]
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: mariadb
      MARIADB_ROOT_PASSWORD: root

  ngrok:
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports: ["4040:4040"]

  flyway:
    environment:
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
      FLYWAY_BASELINE_ON_MIGRATE: true
      FLYWAY_BASELINE_VERSION: 0
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/mariadb
      FLYWAY_USER: root
      FLYWAY_PASSWORD: root
    volumes:
      - ${PWD}/tools/environment/migrations:/flyway/sql

  mock-server:
    volumes:
      - ${PWD}/tools/environment/mock/expectations:/config/expectations
    ports: ["1080:1080"]
