services:
  mariadb:
    image: mariadb:11.2.6@sha256:ff87d49107a1e4878c63c3a3132bfdf628e6732879b8e4ceb72e041206d3aece
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:12.9.0@sha256:558c98dbdb19f47bba16648c9ecc6a021f710ea8804fad946968a0993b0fd89a
    command: migrate
    depends_on:
      mariadb:
        condition: service_healthy

  spring-webflux-aggregator:
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD",
          "busybox",
          "wget",
          "-q",
          "-O",
          "/dev/null",
          "http://localhost:8080/health/ping",
        ]
      interval: 5s
      timeout: 5s
      retries: 60

  spring-telegram-webhook:
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      spring-webflux-aggregator:
        condition: service_healthy

  ngrok:
    image: ngrok/ngrok:3@sha256:14d80d083e5b53145f416bbbd36238336c9de4016c43fd950eb2eb845670583b
    command: http host.docker.internal:5050

  mock-server:
    image: mockserver/mockserver:7.1.0@sha256:c5cb3c49b71245a95e890b0a91d1e8e9e0014d2d53c7958971c9643b0d47ee6e
    profiles: ["mock"]
    command: >
      -logLevel DEBUG 
      -serverPort 1080

volumes:
  mariadb_data:
