services:
  mariadb:
    image: mariadb:11.2.6@sha256:ff87d49107a1e4878c63c3a3132bfdf628e6732879b8e4ceb72e041206d3aece
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:12.6.2@sha256:b31ea37a8f7c3bd29b19932c63259dd8767c67427742b72e8fd5d552f88ff506
    command: migrate
    depends_on:
      mariadb:
        condition: service_healthy

  spring-webflux-aggregator:
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD",
          "busybox",
          "wget",
          "-q",
          "-O",
          "/dev/null",
          "http://localhost:8080/health/ping",
        ]
      interval: 5s
      timeout: 5s
      retries: 60

  spring-telegram-webhook:
    depends_on:
      mariadb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
      spring-webflux-aggregator:
        condition: service_healthy

  ngrok:
    image: ngrok/ngrok:3@sha256:4342588bb2da72355731b78d75e004f96cc6c5fad50fb403cb8f7677b72f4b18
    command: http host.docker.internal:5050

  mock-server:
    image: mockserver/mockserver:6.1.0@sha256:900b7d4c13cc7c5b229de87435278807efb5eb13a1699b681e367c6c96c8b38d
    profiles: ["mock"]
    command: >
      -logLevel DEBUG 
      -serverPort 1080

volumes:
  mariadb_data:
