name: "Test Report"
on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: 🔨Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: 📦Download artifacts
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: 🔬Report summary
        uses: dorny/test-reporter@df6247429542221bc30d46a036ee47af1102c451 # v2
        with:
          name: "🔬Test report: $1 $2"
          artifact: /test-report-(.*)-(.*)/
          path: "**/build/test-results/**/TEST-*.xml"
          reporter: java-junit
